name = "MGA"
uuid = "a88418a5-8dc5-4f1c-8a3e-d5a75ec49c70"
authors = ["Matthijs Arnoldus <m.arnoldus-1@tudelft.nl> and contributors"]
version = "0.1.0"

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[compat]
JuMP = "1"
MathOptInterface = "1"
Distances = "0.10"
julia = "1.6"
