name = "MGA"
uuid = "a88418a5-8dc5-4f1c-8a3e-d5a75ec49c70"
authors = ["Matthijs Arnoldus <m.arnoldus-1@tudelft.nl> and contributors"]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
julia = "1.6"
